# Generated by Django 2.0.5 on 2018-05-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.CharField(max_length=100),
        ),
    ]
